# Generated by Django 3.0.5 on 2020-04-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Push',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('push_image', models.ImageField(upload_to='')),
                ('times_sent', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Pushes',
            },
        ),
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
        migrations.DeleteModel(
            name='Pushes',
        ),
    ]
